import { PinataSDK } from "pinata"

export const pinata = new PinataSDK({
  pinataJwt: `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiJkM2JiYzYzYy1lYzc3LTRlMzMtYjA4OC02M2IwYjQ5ZDhmNmMiLCJlbWFpbCI6InNoYW5nZXNoc2l4aXN2dkBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGluX3BvbGljeSI6eyJyZWdpb25zIjpbeyJkZXNpcmVkUmVwbGljYXRpb25Db3VudCI6MSwiaWQiOiJGUkExIn0seyJkZXNpcmVkUmVwbGljYXRpb25Db3VudCI6MSwiaWQiOiJOWUMxIn1dLCJ2ZXJzaW9uIjoxfSwibWZhX2VuYWJsZWQiOmZhbHNlLCJzdGF0dXMiOiJBQ1RJVkUifSwiYXV0aGVudGljYXRpb25UeXBlIjoic2NvcGVkS2V5Iiwic2NvcGVkS2V5S2V5IjoiYmMxZjNmZjFhOTdmMTNlOTc5NmYiLCJzY29wZWRLZXlTZWNyZXQiOiIwYjAzOTA3ZTI3Yjc1MjBiYzAwNTFmZmY3ZTM0YzdiMjE5YzkyMWNmMzBjOWMwMzM4YjZjMzI5YjY4MDgwYjJkIiwiZXhwIjoxNzgzNjE0NTU1fQ.60MLGaPz5rkYXHsvzJxg9VV-OkayPgIfU3qe4qCiYbc`,
  pinataGateway: `silver-worthy-mosquito-627.mypinata.cloud`
}) 